[tool.poetry]
name = "polus-plugins-transforms-images-image-calculator"
version = "0.2.1"
description = ""
authors = [
    "Nicholas Schaub <nick.schaub@nih.gov>",
    "Najib Ishaq <najib.ishaq@nih.gov>",
]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
bfio = {version = "2.3.3", extras = ["all"]}
# filepattern = "1.4.7"
filepattern = "2.0.4"
typer = "^0.7.0"
tqdm = "^4.65.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"
bump2version = "^1.0.1"
pytest = "^7.3.2"
pytest-xdist = "^3.3.1"
pytest-sugar = "^0.9.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
