[tool.poetry]
name = "polus-images-utils-idr-download"
version = "0.1.0-dev0"
description = "Retrieve the microscopy image data from the idr server"
authors = [
           "Hamdah Shafqat abbasi <hamdahshafqat.abbasi@nih.gov>"
           ]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
python = "3.9.18"
bfio = {version = "^2.3.6", extras = ["all"]}
typer = "^0.7.0"
pydantic = "^2.5.3"
pandas = "2.2.2"
preadator = "0.4.0-dev2"
tqdm = "^4.66.2"

[[tool.poetry.source]]
name = "test"
url = "https://test.pypi.org/simple/"
default = false
secondary = true

[tool.poetry.group.dev.dependencies]
bump2version = "^1.0.1"
flake8 = "^6.0.0"
pre-commit = "^3.2.1"
flake8-docstrings = "^1.7.0"
black = "^23.3.0"
mypy = "^1.1.1"
pytest = "^7.2.2"
ruff = "^0.0.270"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
